dir: "{{.InterfaceDir}}/mocks"
filename: "{{.InterfaceName}}.go"
mockname: "{{.InterfaceName}}"
outpkg: mocks
with-expecter: true
packages:
  github.com/c2fo/vfs/v6:
    config:
      all: true
  github.com/c2fo/vfs/v6/backend/s3:
    config:
      all: true
  github.com/c2fo/vfs/v6/backend/sftp:
    interfaces:
      Client:
      ReadWriteSeekCloser:
  io/fs:
    config:
      dir: "backend/sftp/mocks"
    interfaces:
      FileInfo:
  github.com/c2fo/vfs/v6/backend/ftp/types:
    config:
      all: true
      dir: "backend/ftp/mocks"
