language: go

env:
  - GO111MODULE=on

git:
  depth: 1

install: true

notifications:
  email: false

go:
  - 1.14.x
  - 1.15.x
  - tip

before_install:
  - go get github.com/mattn/goveralls

script:
  - go test -v -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - goveralls -v -debug -coverprofile=coverage.txt -service=travis-ci
  - bash <(curl -s https://codecov.io/bash)
