// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"io/fs"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewFileInfo creates a new instance of FileInfo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFileInfo(t interface {
	mock.TestingT
	Cleanup(func())
}) *FileInfo {
	mock := &FileInfo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// FileInfo is an autogenerated mock type for the FileInfo type
type FileInfo struct {
	mock.Mock
}

type FileInfo_Expecter struct {
	mock *mock.Mock
}

func (_m *FileInfo) EXPECT() *FileInfo_Expecter {
	return &FileInfo_Expecter{mock: &_m.Mock}
}

// IsDir provides a mock function for the type FileInfo
func (_mock *FileInfo) IsDir() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsDir")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// FileInfo_IsDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsDir'
type FileInfo_IsDir_Call struct {
	*mock.Call
}

// IsDir is a helper method to define mock.On call
func (_e *FileInfo_Expecter) IsDir() *FileInfo_IsDir_Call {
	return &FileInfo_IsDir_Call{Call: _e.mock.On("IsDir")}
}

func (_c *FileInfo_IsDir_Call) Run(run func()) *FileInfo_IsDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *FileInfo_IsDir_Call) Return(b bool) *FileInfo_IsDir_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *FileInfo_IsDir_Call) RunAndReturn(run func() bool) *FileInfo_IsDir_Call {
	_c.Call.Return(run)
	return _c
}

// ModTime provides a mock function for the type FileInfo
func (_mock *FileInfo) ModTime() time.Time {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ModTime")
	}

	var r0 time.Time
	if returnFunc, ok := ret.Get(0).(func() time.Time); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	return r0
}

// FileInfo_ModTime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ModTime'
type FileInfo_ModTime_Call struct {
	*mock.Call
}

// ModTime is a helper method to define mock.On call
func (_e *FileInfo_Expecter) ModTime() *FileInfo_ModTime_Call {
	return &FileInfo_ModTime_Call{Call: _e.mock.On("ModTime")}
}

func (_c *FileInfo_ModTime_Call) Run(run func()) *FileInfo_ModTime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *FileInfo_ModTime_Call) Return(time1 time.Time) *FileInfo_ModTime_Call {
	_c.Call.Return(time1)
	return _c
}

func (_c *FileInfo_ModTime_Call) RunAndReturn(run func() time.Time) *FileInfo_ModTime_Call {
	_c.Call.Return(run)
	return _c
}

// Mode provides a mock function for the type FileInfo
func (_mock *FileInfo) Mode() fs.FileMode {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Mode")
	}

	var r0 fs.FileMode
	if returnFunc, ok := ret.Get(0).(func() fs.FileMode); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(fs.FileMode)
	}
	return r0
}

// FileInfo_Mode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Mode'
type FileInfo_Mode_Call struct {
	*mock.Call
}

// Mode is a helper method to define mock.On call
func (_e *FileInfo_Expecter) Mode() *FileInfo_Mode_Call {
	return &FileInfo_Mode_Call{Call: _e.mock.On("Mode")}
}

func (_c *FileInfo_Mode_Call) Run(run func()) *FileInfo_Mode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *FileInfo_Mode_Call) Return(fileMode fs.FileMode) *FileInfo_Mode_Call {
	_c.Call.Return(fileMode)
	return _c
}

func (_c *FileInfo_Mode_Call) RunAndReturn(run func() fs.FileMode) *FileInfo_Mode_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function for the type FileInfo
func (_mock *FileInfo) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// FileInfo_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type FileInfo_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *FileInfo_Expecter) Name() *FileInfo_Name_Call {
	return &FileInfo_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *FileInfo_Name_Call) Run(run func()) *FileInfo_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *FileInfo_Name_Call) Return(s string) *FileInfo_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *FileInfo_Name_Call) RunAndReturn(run func() string) *FileInfo_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Size provides a mock function for the type FileInfo
func (_mock *FileInfo) Size() int64 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Size")
	}

	var r0 int64
	if returnFunc, ok := ret.Get(0).(func() int64); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int64)
	}
	return r0
}

// FileInfo_Size_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Size'
type FileInfo_Size_Call struct {
	*mock.Call
}

// Size is a helper method to define mock.On call
func (_e *FileInfo_Expecter) Size() *FileInfo_Size_Call {
	return &FileInfo_Size_Call{Call: _e.mock.On("Size")}
}

func (_c *FileInfo_Size_Call) Run(run func()) *FileInfo_Size_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *FileInfo_Size_Call) Return(n int64) *FileInfo_Size_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *FileInfo_Size_Call) RunAndReturn(run func() int64) *FileInfo_Size_Call {
	_c.Call.Return(run)
	return _c
}

// Sys provides a mock function for the type FileInfo
func (_mock *FileInfo) Sys() any {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Sys")
	}

	var r0 any
	if returnFunc, ok := ret.Get(0).(func() any); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	return r0
}

// FileInfo_Sys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sys'
type FileInfo_Sys_Call struct {
	*mock.Call
}

// Sys is a helper method to define mock.On call
func (_e *FileInfo_Expecter) Sys() *FileInfo_Sys_Call {
	return &FileInfo_Sys_Call{Call: _e.mock.On("Sys")}
}

func (_c *FileInfo_Sys_Call) Run(run func()) *FileInfo_Sys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *FileInfo_Sys_Call) Return(v any) *FileInfo_Sys_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *FileInfo_Sys_Call) RunAndReturn(run func() any) *FileInfo_Sys_Call {
	_c.Call.Return(run)
	return _c
}
