// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ReadWriteSeekCloser is an autogenerated mock type for the ReadWriteSeekCloser type
type ReadWriteSeekCloser struct {
	mock.Mock
}

type ReadWriteSeekCloser_Expecter struct {
	mock *mock.Mock
}

func (_m *ReadWriteSeekCloser) EXPECT() *ReadWriteSeekCloser_Expecter {
	return &ReadWriteSeekCloser_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with given fields:
func (_m *ReadWriteSeekCloser) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReadWriteSeekCloser_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type ReadWriteSeekCloser_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *ReadWriteSeekCloser_Expecter) Close() *ReadWriteSeekCloser_Close_Call {
	return &ReadWriteSeekCloser_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *ReadWriteSeekCloser_Close_Call) Run(run func()) *ReadWriteSeekCloser_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ReadWriteSeekCloser_Close_Call) Return(_a0 error) *ReadWriteSeekCloser_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ReadWriteSeekCloser_Close_Call) RunAndReturn(run func() error) *ReadWriteSeekCloser_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Read provides a mock function with given fields: p
func (_m *ReadWriteSeekCloser) Read(p []byte) (int, error) {
	ret := _m.Called(p)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte) (int, error)); ok {
		return rf(p)
	}
	if rf, ok := ret.Get(0).(func([]byte) int); ok {
		r0 = rf(p)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReadWriteSeekCloser_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type ReadWriteSeekCloser_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - p []byte
func (_e *ReadWriteSeekCloser_Expecter) Read(p interface{}) *ReadWriteSeekCloser_Read_Call {
	return &ReadWriteSeekCloser_Read_Call{Call: _e.mock.On("Read", p)}
}

func (_c *ReadWriteSeekCloser_Read_Call) Run(run func(p []byte)) *ReadWriteSeekCloser_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *ReadWriteSeekCloser_Read_Call) Return(n int, err error) *ReadWriteSeekCloser_Read_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *ReadWriteSeekCloser_Read_Call) RunAndReturn(run func([]byte) (int, error)) *ReadWriteSeekCloser_Read_Call {
	_c.Call.Return(run)
	return _c
}

// Seek provides a mock function with given fields: offset, whence
func (_m *ReadWriteSeekCloser) Seek(offset int64, whence int) (int64, error) {
	ret := _m.Called(offset, whence)

	if len(ret) == 0 {
		panic("no return value specified for Seek")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(int64, int) (int64, error)); ok {
		return rf(offset, whence)
	}
	if rf, ok := ret.Get(0).(func(int64, int) int64); ok {
		r0 = rf(offset, whence)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(int64, int) error); ok {
		r1 = rf(offset, whence)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReadWriteSeekCloser_Seek_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Seek'
type ReadWriteSeekCloser_Seek_Call struct {
	*mock.Call
}

// Seek is a helper method to define mock.On call
//   - offset int64
//   - whence int
func (_e *ReadWriteSeekCloser_Expecter) Seek(offset interface{}, whence interface{}) *ReadWriteSeekCloser_Seek_Call {
	return &ReadWriteSeekCloser_Seek_Call{Call: _e.mock.On("Seek", offset, whence)}
}

func (_c *ReadWriteSeekCloser_Seek_Call) Run(run func(offset int64, whence int)) *ReadWriteSeekCloser_Seek_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64), args[1].(int))
	})
	return _c
}

func (_c *ReadWriteSeekCloser_Seek_Call) Return(_a0 int64, _a1 error) *ReadWriteSeekCloser_Seek_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReadWriteSeekCloser_Seek_Call) RunAndReturn(run func(int64, int) (int64, error)) *ReadWriteSeekCloser_Seek_Call {
	_c.Call.Return(run)
	return _c
}

// Write provides a mock function with given fields: p
func (_m *ReadWriteSeekCloser) Write(p []byte) (int, error) {
	ret := _m.Called(p)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte) (int, error)); ok {
		return rf(p)
	}
	if rf, ok := ret.Get(0).(func([]byte) int); ok {
		r0 = rf(p)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReadWriteSeekCloser_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type ReadWriteSeekCloser_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - p []byte
func (_e *ReadWriteSeekCloser_Expecter) Write(p interface{}) *ReadWriteSeekCloser_Write_Call {
	return &ReadWriteSeekCloser_Write_Call{Call: _e.mock.On("Write", p)}
}

func (_c *ReadWriteSeekCloser_Write_Call) Run(run func(p []byte)) *ReadWriteSeekCloser_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *ReadWriteSeekCloser_Write_Call) Return(n int, err error) *ReadWriteSeekCloser_Write_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *ReadWriteSeekCloser_Write_Call) RunAndReturn(run func([]byte) (int, error)) *ReadWriteSeekCloser_Write_Call {
	_c.Call.Return(run)
	return _c
}

// NewReadWriteSeekCloser creates a new instance of ReadWriteSeekCloser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReadWriteSeekCloser(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReadWriteSeekCloser {
	mock := &ReadWriteSeekCloser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
