// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	io "io"

	jlaffayeftp "github.com/jlaffaye/ftp"
	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

type Client_Expecter struct {
	mock *mock.Mock
}

func (_m *Client) EXPECT() *Client_Expecter {
	return &Client_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: path
func (_m *Client) Delete(path string) error {
	ret := _m.Called(path)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(path)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Client_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type Client_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//  - path string
func (_e *Client_Expecter) Delete(path interface{}) *Client_Delete_Call {
	return &Client_Delete_Call{Call: _e.mock.On("Delete", path)}
}

func (_c *Client_Delete_Call) Run(run func(path string)) *Client_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Client_Delete_Call) Return(_a0 error) *Client_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

// List provides a mock function with given fields: p
func (_m *Client) List(p string) ([]*jlaffayeftp.Entry, error) {
	ret := _m.Called(p)

	var r0 []*jlaffayeftp.Entry
	if rf, ok := ret.Get(0).(func(string) []*jlaffayeftp.Entry); ok {
		r0 = rf(p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*jlaffayeftp.Entry)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type Client_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//  - p string
func (_e *Client_Expecter) List(p interface{}) *Client_List_Call {
	return &Client_List_Call{Call: _e.mock.On("List", p)}
}

func (_c *Client_List_Call) Run(run func(p string)) *Client_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Client_List_Call) Return(_a0 []*jlaffayeftp.Entry, _a1 error) *Client_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// Login provides a mock function with given fields: user, password
func (_m *Client) Login(user string, password string) error {
	ret := _m.Called(user, password)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(user, password)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Client_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type Client_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//  - user string
//  - password string
func (_e *Client_Expecter) Login(user interface{}, password interface{}) *Client_Login_Call {
	return &Client_Login_Call{Call: _e.mock.On("Login", user, password)}
}

func (_c *Client_Login_Call) Run(run func(user string, password string)) *Client_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *Client_Login_Call) Return(_a0 error) *Client_Login_Call {
	_c.Call.Return(_a0)
	return _c
}

// MakeDir provides a mock function with given fields: path
func (_m *Client) MakeDir(path string) error {
	ret := _m.Called(path)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(path)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Client_MakeDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MakeDir'
type Client_MakeDir_Call struct {
	*mock.Call
}

// MakeDir is a helper method to define mock.On call
//  - path string
func (_e *Client_Expecter) MakeDir(path interface{}) *Client_MakeDir_Call {
	return &Client_MakeDir_Call{Call: _e.mock.On("MakeDir", path)}
}

func (_c *Client_MakeDir_Call) Run(run func(path string)) *Client_MakeDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Client_MakeDir_Call) Return(_a0 error) *Client_MakeDir_Call {
	_c.Call.Return(_a0)
	return _c
}

// Quit provides a mock function with given fields:
func (_m *Client) Quit() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Client_Quit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Quit'
type Client_Quit_Call struct {
	*mock.Call
}

// Quit is a helper method to define mock.On call
func (_e *Client_Expecter) Quit() *Client_Quit_Call {
	return &Client_Quit_Call{Call: _e.mock.On("Quit")}
}

func (_c *Client_Quit_Call) Run(run func()) *Client_Quit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Client_Quit_Call) Return(_a0 error) *Client_Quit_Call {
	_c.Call.Return(_a0)
	return _c
}

// Rename provides a mock function with given fields: from, to
func (_m *Client) Rename(from string, to string) error {
	ret := _m.Called(from, to)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(from, to)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Client_Rename_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rename'
type Client_Rename_Call struct {
	*mock.Call
}

// Rename is a helper method to define mock.On call
//  - from string
//  - to string
func (_e *Client_Expecter) Rename(from interface{}, to interface{}) *Client_Rename_Call {
	return &Client_Rename_Call{Call: _e.mock.On("Rename", from, to)}
}

func (_c *Client_Rename_Call) Run(run func(from string, to string)) *Client_Rename_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *Client_Rename_Call) Return(_a0 error) *Client_Rename_Call {
	_c.Call.Return(_a0)
	return _c
}

// RetrFrom provides a mock function with given fields: path, offset
func (_m *Client) RetrFrom(path string, offset uint64) (*jlaffayeftp.Response, error) {
	ret := _m.Called(path, offset)

	var r0 *jlaffayeftp.Response
	if rf, ok := ret.Get(0).(func(string, uint64) *jlaffayeftp.Response); ok {
		r0 = rf(path, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jlaffayeftp.Response)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, uint64) error); ok {
		r1 = rf(path, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_RetrFrom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RetrFrom'
type Client_RetrFrom_Call struct {
	*mock.Call
}

// RetrFrom is a helper method to define mock.On call
//  - path string
//  - offset uint64
func (_e *Client_Expecter) RetrFrom(path interface{}, offset interface{}) *Client_RetrFrom_Call {
	return &Client_RetrFrom_Call{Call: _e.mock.On("RetrFrom", path, offset)}
}

func (_c *Client_RetrFrom_Call) Run(run func(path string, offset uint64)) *Client_RetrFrom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(uint64))
	})
	return _c
}

func (_c *Client_RetrFrom_Call) Return(_a0 *jlaffayeftp.Response, _a1 error) *Client_RetrFrom_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// StorFrom provides a mock function with given fields: path, r, offset
func (_m *Client) StorFrom(path string, r io.Reader, offset uint64) error {
	ret := _m.Called(path, r, offset)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, io.Reader, uint64) error); ok {
		r0 = rf(path, r, offset)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Client_StorFrom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StorFrom'
type Client_StorFrom_Call struct {
	*mock.Call
}

// StorFrom is a helper method to define mock.On call
//  - path string
//  - r io.Reader
//  - offset uint64
func (_e *Client_Expecter) StorFrom(path interface{}, r interface{}, offset interface{}) *Client_StorFrom_Call {
	return &Client_StorFrom_Call{Call: _e.mock.On("StorFrom", path, r, offset)}
}

func (_c *Client_StorFrom_Call) Run(run func(path string, r io.Reader, offset uint64)) *Client_StorFrom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(io.Reader), args[2].(uint64))
	})
	return _c
}

func (_c *Client_StorFrom_Call) Return(_a0 error) *Client_StorFrom_Call {
	_c.Call.Return(_a0)
	return _c
}

type mockConstructorTestingTNewClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewClient(t mockConstructorTestingTNewClient) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
