// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Options is an autogenerated mock type for the Options type
type Options struct {
	mock.Mock
}

type Options_Expecter struct {
	mock *mock.Mock
}

func (_m *Options) EXPECT() *Options_Expecter {
	return &Options_Expecter{mock: &_m.Mock}
}

// NewOptions creates a new instance of Options. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOptions(t interface {
	mock.TestingT
	Cleanup(func())
}) *Options {
	mock := &Options{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
