// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/s3"
	mock "github.com/stretchr/testify/mock"
)

// NewBackendClient creates a new instance of BackendClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBackendClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *BackendClient {
	mock := &BackendClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// BackendClient is an autogenerated mock type for the backendClient type
type BackendClient struct {
	mock.Mock
}

type BackendClient_Expecter struct {
	mock *mock.Mock
}

func (_m *BackendClient) EXPECT() *BackendClient_Expecter {
	return &BackendClient_Expecter{mock: &_m.Mock}
}

// AbortMultipartUpload provides a mock function for the type BackendClient
func (_mock *BackendClient) AbortMultipartUpload(context1 context.Context, abortMultipartUploadInput *s3.AbortMultipartUploadInput, fns ...func(*s3.Options)) (*s3.AbortMultipartUploadOutput, error) {
	var tmpRet mock.Arguments
	if len(fns) > 0 {
		tmpRet = _mock.Called(context1, abortMultipartUploadInput, fns)
	} else {
		tmpRet = _mock.Called(context1, abortMultipartUploadInput)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for AbortMultipartUpload")
	}

	var r0 *s3.AbortMultipartUploadOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.AbortMultipartUploadInput, ...func(*s3.Options)) (*s3.AbortMultipartUploadOutput, error)); ok {
		return returnFunc(context1, abortMultipartUploadInput, fns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.AbortMultipartUploadInput, ...func(*s3.Options)) *s3.AbortMultipartUploadOutput); ok {
		r0 = returnFunc(context1, abortMultipartUploadInput, fns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*s3.AbortMultipartUploadOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *s3.AbortMultipartUploadInput, ...func(*s3.Options)) error); ok {
		r1 = returnFunc(context1, abortMultipartUploadInput, fns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// BackendClient_AbortMultipartUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AbortMultipartUpload'
type BackendClient_AbortMultipartUpload_Call struct {
	*mock.Call
}

// AbortMultipartUpload is a helper method to define mock.On call
//   - context1 context.Context
//   - abortMultipartUploadInput *s3.AbortMultipartUploadInput
//   - fns ...func(*s3.Options)
func (_e *BackendClient_Expecter) AbortMultipartUpload(context1 interface{}, abortMultipartUploadInput interface{}, fns ...interface{}) *BackendClient_AbortMultipartUpload_Call {
	return &BackendClient_AbortMultipartUpload_Call{Call: _e.mock.On("AbortMultipartUpload",
		append([]interface{}{context1, abortMultipartUploadInput}, fns...)...)}
}

func (_c *BackendClient_AbortMultipartUpload_Call) Run(run func(context1 context.Context, abortMultipartUploadInput *s3.AbortMultipartUploadInput, fns ...func(*s3.Options))) *BackendClient_AbortMultipartUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *s3.AbortMultipartUploadInput
		if args[1] != nil {
			arg1 = args[1].(*s3.AbortMultipartUploadInput)
		}
		var arg2 []func(*s3.Options)
		var variadicArgs []func(*s3.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*s3.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *BackendClient_AbortMultipartUpload_Call) Return(abortMultipartUploadOutput *s3.AbortMultipartUploadOutput, err error) *BackendClient_AbortMultipartUpload_Call {
	_c.Call.Return(abortMultipartUploadOutput, err)
	return _c
}

func (_c *BackendClient_AbortMultipartUpload_Call) RunAndReturn(run func(context1 context.Context, abortMultipartUploadInput *s3.AbortMultipartUploadInput, fns ...func(*s3.Options)) (*s3.AbortMultipartUploadOutput, error)) *BackendClient_AbortMultipartUpload_Call {
	_c.Call.Return(run)
	return _c
}

// CompleteMultipartUpload provides a mock function for the type BackendClient
func (_mock *BackendClient) CompleteMultipartUpload(context1 context.Context, completeMultipartUploadInput *s3.CompleteMultipartUploadInput, fns ...func(*s3.Options)) (*s3.CompleteMultipartUploadOutput, error) {
	var tmpRet mock.Arguments
	if len(fns) > 0 {
		tmpRet = _mock.Called(context1, completeMultipartUploadInput, fns)
	} else {
		tmpRet = _mock.Called(context1, completeMultipartUploadInput)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for CompleteMultipartUpload")
	}

	var r0 *s3.CompleteMultipartUploadOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.CompleteMultipartUploadInput, ...func(*s3.Options)) (*s3.CompleteMultipartUploadOutput, error)); ok {
		return returnFunc(context1, completeMultipartUploadInput, fns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.CompleteMultipartUploadInput, ...func(*s3.Options)) *s3.CompleteMultipartUploadOutput); ok {
		r0 = returnFunc(context1, completeMultipartUploadInput, fns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*s3.CompleteMultipartUploadOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *s3.CompleteMultipartUploadInput, ...func(*s3.Options)) error); ok {
		r1 = returnFunc(context1, completeMultipartUploadInput, fns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// BackendClient_CompleteMultipartUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteMultipartUpload'
type BackendClient_CompleteMultipartUpload_Call struct {
	*mock.Call
}

// CompleteMultipartUpload is a helper method to define mock.On call
//   - context1 context.Context
//   - completeMultipartUploadInput *s3.CompleteMultipartUploadInput
//   - fns ...func(*s3.Options)
func (_e *BackendClient_Expecter) CompleteMultipartUpload(context1 interface{}, completeMultipartUploadInput interface{}, fns ...interface{}) *BackendClient_CompleteMultipartUpload_Call {
	return &BackendClient_CompleteMultipartUpload_Call{Call: _e.mock.On("CompleteMultipartUpload",
		append([]interface{}{context1, completeMultipartUploadInput}, fns...)...)}
}

func (_c *BackendClient_CompleteMultipartUpload_Call) Run(run func(context1 context.Context, completeMultipartUploadInput *s3.CompleteMultipartUploadInput, fns ...func(*s3.Options))) *BackendClient_CompleteMultipartUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *s3.CompleteMultipartUploadInput
		if args[1] != nil {
			arg1 = args[1].(*s3.CompleteMultipartUploadInput)
		}
		var arg2 []func(*s3.Options)
		var variadicArgs []func(*s3.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*s3.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *BackendClient_CompleteMultipartUpload_Call) Return(completeMultipartUploadOutput *s3.CompleteMultipartUploadOutput, err error) *BackendClient_CompleteMultipartUpload_Call {
	_c.Call.Return(completeMultipartUploadOutput, err)
	return _c
}

func (_c *BackendClient_CompleteMultipartUpload_Call) RunAndReturn(run func(context1 context.Context, completeMultipartUploadInput *s3.CompleteMultipartUploadInput, fns ...func(*s3.Options)) (*s3.CompleteMultipartUploadOutput, error)) *BackendClient_CompleteMultipartUpload_Call {
	_c.Call.Return(run)
	return _c
}

// CopyObject provides a mock function for the type BackendClient
func (_mock *BackendClient) CopyObject(context1 context.Context, copyObjectInput *s3.CopyObjectInput, fns ...func(*s3.Options)) (*s3.CopyObjectOutput, error) {
	var tmpRet mock.Arguments
	if len(fns) > 0 {
		tmpRet = _mock.Called(context1, copyObjectInput, fns)
	} else {
		tmpRet = _mock.Called(context1, copyObjectInput)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for CopyObject")
	}

	var r0 *s3.CopyObjectOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.CopyObjectInput, ...func(*s3.Options)) (*s3.CopyObjectOutput, error)); ok {
		return returnFunc(context1, copyObjectInput, fns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.CopyObjectInput, ...func(*s3.Options)) *s3.CopyObjectOutput); ok {
		r0 = returnFunc(context1, copyObjectInput, fns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*s3.CopyObjectOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *s3.CopyObjectInput, ...func(*s3.Options)) error); ok {
		r1 = returnFunc(context1, copyObjectInput, fns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// BackendClient_CopyObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CopyObject'
type BackendClient_CopyObject_Call struct {
	*mock.Call
}

// CopyObject is a helper method to define mock.On call
//   - context1 context.Context
//   - copyObjectInput *s3.CopyObjectInput
//   - fns ...func(*s3.Options)
func (_e *BackendClient_Expecter) CopyObject(context1 interface{}, copyObjectInput interface{}, fns ...interface{}) *BackendClient_CopyObject_Call {
	return &BackendClient_CopyObject_Call{Call: _e.mock.On("CopyObject",
		append([]interface{}{context1, copyObjectInput}, fns...)...)}
}

func (_c *BackendClient_CopyObject_Call) Run(run func(context1 context.Context, copyObjectInput *s3.CopyObjectInput, fns ...func(*s3.Options))) *BackendClient_CopyObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *s3.CopyObjectInput
		if args[1] != nil {
			arg1 = args[1].(*s3.CopyObjectInput)
		}
		var arg2 []func(*s3.Options)
		var variadicArgs []func(*s3.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*s3.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *BackendClient_CopyObject_Call) Return(copyObjectOutput *s3.CopyObjectOutput, err error) *BackendClient_CopyObject_Call {
	_c.Call.Return(copyObjectOutput, err)
	return _c
}

func (_c *BackendClient_CopyObject_Call) RunAndReturn(run func(context1 context.Context, copyObjectInput *s3.CopyObjectInput, fns ...func(*s3.Options)) (*s3.CopyObjectOutput, error)) *BackendClient_CopyObject_Call {
	_c.Call.Return(run)
	return _c
}

// CreateMultipartUpload provides a mock function for the type BackendClient
func (_mock *BackendClient) CreateMultipartUpload(context1 context.Context, createMultipartUploadInput *s3.CreateMultipartUploadInput, fns ...func(*s3.Options)) (*s3.CreateMultipartUploadOutput, error) {
	var tmpRet mock.Arguments
	if len(fns) > 0 {
		tmpRet = _mock.Called(context1, createMultipartUploadInput, fns)
	} else {
		tmpRet = _mock.Called(context1, createMultipartUploadInput)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for CreateMultipartUpload")
	}

	var r0 *s3.CreateMultipartUploadOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.CreateMultipartUploadInput, ...func(*s3.Options)) (*s3.CreateMultipartUploadOutput, error)); ok {
		return returnFunc(context1, createMultipartUploadInput, fns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.CreateMultipartUploadInput, ...func(*s3.Options)) *s3.CreateMultipartUploadOutput); ok {
		r0 = returnFunc(context1, createMultipartUploadInput, fns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*s3.CreateMultipartUploadOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *s3.CreateMultipartUploadInput, ...func(*s3.Options)) error); ok {
		r1 = returnFunc(context1, createMultipartUploadInput, fns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// BackendClient_CreateMultipartUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateMultipartUpload'
type BackendClient_CreateMultipartUpload_Call struct {
	*mock.Call
}

// CreateMultipartUpload is a helper method to define mock.On call
//   - context1 context.Context
//   - createMultipartUploadInput *s3.CreateMultipartUploadInput
//   - fns ...func(*s3.Options)
func (_e *BackendClient_Expecter) CreateMultipartUpload(context1 interface{}, createMultipartUploadInput interface{}, fns ...interface{}) *BackendClient_CreateMultipartUpload_Call {
	return &BackendClient_CreateMultipartUpload_Call{Call: _e.mock.On("CreateMultipartUpload",
		append([]interface{}{context1, createMultipartUploadInput}, fns...)...)}
}

func (_c *BackendClient_CreateMultipartUpload_Call) Run(run func(context1 context.Context, createMultipartUploadInput *s3.CreateMultipartUploadInput, fns ...func(*s3.Options))) *BackendClient_CreateMultipartUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *s3.CreateMultipartUploadInput
		if args[1] != nil {
			arg1 = args[1].(*s3.CreateMultipartUploadInput)
		}
		var arg2 []func(*s3.Options)
		var variadicArgs []func(*s3.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*s3.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *BackendClient_CreateMultipartUpload_Call) Return(createMultipartUploadOutput *s3.CreateMultipartUploadOutput, err error) *BackendClient_CreateMultipartUpload_Call {
	_c.Call.Return(createMultipartUploadOutput, err)
	return _c
}

func (_c *BackendClient_CreateMultipartUpload_Call) RunAndReturn(run func(context1 context.Context, createMultipartUploadInput *s3.CreateMultipartUploadInput, fns ...func(*s3.Options)) (*s3.CreateMultipartUploadOutput, error)) *BackendClient_CreateMultipartUpload_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteObject provides a mock function for the type BackendClient
func (_mock *BackendClient) DeleteObject(context1 context.Context, deleteObjectInput *s3.DeleteObjectInput, fns ...func(*s3.Options)) (*s3.DeleteObjectOutput, error) {
	var tmpRet mock.Arguments
	if len(fns) > 0 {
		tmpRet = _mock.Called(context1, deleteObjectInput, fns)
	} else {
		tmpRet = _mock.Called(context1, deleteObjectInput)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DeleteObject")
	}

	var r0 *s3.DeleteObjectOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.DeleteObjectInput, ...func(*s3.Options)) (*s3.DeleteObjectOutput, error)); ok {
		return returnFunc(context1, deleteObjectInput, fns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.DeleteObjectInput, ...func(*s3.Options)) *s3.DeleteObjectOutput); ok {
		r0 = returnFunc(context1, deleteObjectInput, fns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*s3.DeleteObjectOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *s3.DeleteObjectInput, ...func(*s3.Options)) error); ok {
		r1 = returnFunc(context1, deleteObjectInput, fns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// BackendClient_DeleteObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteObject'
type BackendClient_DeleteObject_Call struct {
	*mock.Call
}

// DeleteObject is a helper method to define mock.On call
//   - context1 context.Context
//   - deleteObjectInput *s3.DeleteObjectInput
//   - fns ...func(*s3.Options)
func (_e *BackendClient_Expecter) DeleteObject(context1 interface{}, deleteObjectInput interface{}, fns ...interface{}) *BackendClient_DeleteObject_Call {
	return &BackendClient_DeleteObject_Call{Call: _e.mock.On("DeleteObject",
		append([]interface{}{context1, deleteObjectInput}, fns...)...)}
}

func (_c *BackendClient_DeleteObject_Call) Run(run func(context1 context.Context, deleteObjectInput *s3.DeleteObjectInput, fns ...func(*s3.Options))) *BackendClient_DeleteObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *s3.DeleteObjectInput
		if args[1] != nil {
			arg1 = args[1].(*s3.DeleteObjectInput)
		}
		var arg2 []func(*s3.Options)
		var variadicArgs []func(*s3.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*s3.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *BackendClient_DeleteObject_Call) Return(deleteObjectOutput *s3.DeleteObjectOutput, err error) *BackendClient_DeleteObject_Call {
	_c.Call.Return(deleteObjectOutput, err)
	return _c
}

func (_c *BackendClient_DeleteObject_Call) RunAndReturn(run func(context1 context.Context, deleteObjectInput *s3.DeleteObjectInput, fns ...func(*s3.Options)) (*s3.DeleteObjectOutput, error)) *BackendClient_DeleteObject_Call {
	_c.Call.Return(run)
	return _c
}

// GetObject provides a mock function for the type BackendClient
func (_mock *BackendClient) GetObject(context1 context.Context, getObjectInput *s3.GetObjectInput, fns ...func(*s3.Options)) (*s3.GetObjectOutput, error) {
	var tmpRet mock.Arguments
	if len(fns) > 0 {
		tmpRet = _mock.Called(context1, getObjectInput, fns)
	} else {
		tmpRet = _mock.Called(context1, getObjectInput)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetObject")
	}

	var r0 *s3.GetObjectOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.GetObjectInput, ...func(*s3.Options)) (*s3.GetObjectOutput, error)); ok {
		return returnFunc(context1, getObjectInput, fns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.GetObjectInput, ...func(*s3.Options)) *s3.GetObjectOutput); ok {
		r0 = returnFunc(context1, getObjectInput, fns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*s3.GetObjectOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *s3.GetObjectInput, ...func(*s3.Options)) error); ok {
		r1 = returnFunc(context1, getObjectInput, fns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// BackendClient_GetObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetObject'
type BackendClient_GetObject_Call struct {
	*mock.Call
}

// GetObject is a helper method to define mock.On call
//   - context1 context.Context
//   - getObjectInput *s3.GetObjectInput
//   - fns ...func(*s3.Options)
func (_e *BackendClient_Expecter) GetObject(context1 interface{}, getObjectInput interface{}, fns ...interface{}) *BackendClient_GetObject_Call {
	return &BackendClient_GetObject_Call{Call: _e.mock.On("GetObject",
		append([]interface{}{context1, getObjectInput}, fns...)...)}
}

func (_c *BackendClient_GetObject_Call) Run(run func(context1 context.Context, getObjectInput *s3.GetObjectInput, fns ...func(*s3.Options))) *BackendClient_GetObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *s3.GetObjectInput
		if args[1] != nil {
			arg1 = args[1].(*s3.GetObjectInput)
		}
		var arg2 []func(*s3.Options)
		var variadicArgs []func(*s3.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*s3.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *BackendClient_GetObject_Call) Return(getObjectOutput *s3.GetObjectOutput, err error) *BackendClient_GetObject_Call {
	_c.Call.Return(getObjectOutput, err)
	return _c
}

func (_c *BackendClient_GetObject_Call) RunAndReturn(run func(context1 context.Context, getObjectInput *s3.GetObjectInput, fns ...func(*s3.Options)) (*s3.GetObjectOutput, error)) *BackendClient_GetObject_Call {
	_c.Call.Return(run)
	return _c
}

// HeadBucket provides a mock function for the type BackendClient
func (_mock *BackendClient) HeadBucket(context1 context.Context, headBucketInput *s3.HeadBucketInput, fns ...func(*s3.Options)) (*s3.HeadBucketOutput, error) {
	var tmpRet mock.Arguments
	if len(fns) > 0 {
		tmpRet = _mock.Called(context1, headBucketInput, fns)
	} else {
		tmpRet = _mock.Called(context1, headBucketInput)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for HeadBucket")
	}

	var r0 *s3.HeadBucketOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.HeadBucketInput, ...func(*s3.Options)) (*s3.HeadBucketOutput, error)); ok {
		return returnFunc(context1, headBucketInput, fns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.HeadBucketInput, ...func(*s3.Options)) *s3.HeadBucketOutput); ok {
		r0 = returnFunc(context1, headBucketInput, fns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*s3.HeadBucketOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *s3.HeadBucketInput, ...func(*s3.Options)) error); ok {
		r1 = returnFunc(context1, headBucketInput, fns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// BackendClient_HeadBucket_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HeadBucket'
type BackendClient_HeadBucket_Call struct {
	*mock.Call
}

// HeadBucket is a helper method to define mock.On call
//   - context1 context.Context
//   - headBucketInput *s3.HeadBucketInput
//   - fns ...func(*s3.Options)
func (_e *BackendClient_Expecter) HeadBucket(context1 interface{}, headBucketInput interface{}, fns ...interface{}) *BackendClient_HeadBucket_Call {
	return &BackendClient_HeadBucket_Call{Call: _e.mock.On("HeadBucket",
		append([]interface{}{context1, headBucketInput}, fns...)...)}
}

func (_c *BackendClient_HeadBucket_Call) Run(run func(context1 context.Context, headBucketInput *s3.HeadBucketInput, fns ...func(*s3.Options))) *BackendClient_HeadBucket_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *s3.HeadBucketInput
		if args[1] != nil {
			arg1 = args[1].(*s3.HeadBucketInput)
		}
		var arg2 []func(*s3.Options)
		var variadicArgs []func(*s3.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*s3.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *BackendClient_HeadBucket_Call) Return(headBucketOutput *s3.HeadBucketOutput, err error) *BackendClient_HeadBucket_Call {
	_c.Call.Return(headBucketOutput, err)
	return _c
}

func (_c *BackendClient_HeadBucket_Call) RunAndReturn(run func(context1 context.Context, headBucketInput *s3.HeadBucketInput, fns ...func(*s3.Options)) (*s3.HeadBucketOutput, error)) *BackendClient_HeadBucket_Call {
	_c.Call.Return(run)
	return _c
}

// HeadObject provides a mock function for the type BackendClient
func (_mock *BackendClient) HeadObject(context1 context.Context, headObjectInput *s3.HeadObjectInput, fns ...func(*s3.Options)) (*s3.HeadObjectOutput, error) {
	var tmpRet mock.Arguments
	if len(fns) > 0 {
		tmpRet = _mock.Called(context1, headObjectInput, fns)
	} else {
		tmpRet = _mock.Called(context1, headObjectInput)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for HeadObject")
	}

	var r0 *s3.HeadObjectOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.HeadObjectInput, ...func(*s3.Options)) (*s3.HeadObjectOutput, error)); ok {
		return returnFunc(context1, headObjectInput, fns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.HeadObjectInput, ...func(*s3.Options)) *s3.HeadObjectOutput); ok {
		r0 = returnFunc(context1, headObjectInput, fns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*s3.HeadObjectOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *s3.HeadObjectInput, ...func(*s3.Options)) error); ok {
		r1 = returnFunc(context1, headObjectInput, fns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// BackendClient_HeadObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HeadObject'
type BackendClient_HeadObject_Call struct {
	*mock.Call
}

// HeadObject is a helper method to define mock.On call
//   - context1 context.Context
//   - headObjectInput *s3.HeadObjectInput
//   - fns ...func(*s3.Options)
func (_e *BackendClient_Expecter) HeadObject(context1 interface{}, headObjectInput interface{}, fns ...interface{}) *BackendClient_HeadObject_Call {
	return &BackendClient_HeadObject_Call{Call: _e.mock.On("HeadObject",
		append([]interface{}{context1, headObjectInput}, fns...)...)}
}

func (_c *BackendClient_HeadObject_Call) Run(run func(context1 context.Context, headObjectInput *s3.HeadObjectInput, fns ...func(*s3.Options))) *BackendClient_HeadObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *s3.HeadObjectInput
		if args[1] != nil {
			arg1 = args[1].(*s3.HeadObjectInput)
		}
		var arg2 []func(*s3.Options)
		var variadicArgs []func(*s3.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*s3.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *BackendClient_HeadObject_Call) Return(headObjectOutput *s3.HeadObjectOutput, err error) *BackendClient_HeadObject_Call {
	_c.Call.Return(headObjectOutput, err)
	return _c
}

func (_c *BackendClient_HeadObject_Call) RunAndReturn(run func(context1 context.Context, headObjectInput *s3.HeadObjectInput, fns ...func(*s3.Options)) (*s3.HeadObjectOutput, error)) *BackendClient_HeadObject_Call {
	_c.Call.Return(run)
	return _c
}

// ListObjectVersions provides a mock function for the type BackendClient
func (_mock *BackendClient) ListObjectVersions(context1 context.Context, listObjectVersionsInput *s3.ListObjectVersionsInput, fns ...func(*s3.Options)) (*s3.ListObjectVersionsOutput, error) {
	var tmpRet mock.Arguments
	if len(fns) > 0 {
		tmpRet = _mock.Called(context1, listObjectVersionsInput, fns)
	} else {
		tmpRet = _mock.Called(context1, listObjectVersionsInput)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ListObjectVersions")
	}

	var r0 *s3.ListObjectVersionsOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.ListObjectVersionsInput, ...func(*s3.Options)) (*s3.ListObjectVersionsOutput, error)); ok {
		return returnFunc(context1, listObjectVersionsInput, fns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.ListObjectVersionsInput, ...func(*s3.Options)) *s3.ListObjectVersionsOutput); ok {
		r0 = returnFunc(context1, listObjectVersionsInput, fns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*s3.ListObjectVersionsOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *s3.ListObjectVersionsInput, ...func(*s3.Options)) error); ok {
		r1 = returnFunc(context1, listObjectVersionsInput, fns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// BackendClient_ListObjectVersions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListObjectVersions'
type BackendClient_ListObjectVersions_Call struct {
	*mock.Call
}

// ListObjectVersions is a helper method to define mock.On call
//   - context1 context.Context
//   - listObjectVersionsInput *s3.ListObjectVersionsInput
//   - fns ...func(*s3.Options)
func (_e *BackendClient_Expecter) ListObjectVersions(context1 interface{}, listObjectVersionsInput interface{}, fns ...interface{}) *BackendClient_ListObjectVersions_Call {
	return &BackendClient_ListObjectVersions_Call{Call: _e.mock.On("ListObjectVersions",
		append([]interface{}{context1, listObjectVersionsInput}, fns...)...)}
}

func (_c *BackendClient_ListObjectVersions_Call) Run(run func(context1 context.Context, listObjectVersionsInput *s3.ListObjectVersionsInput, fns ...func(*s3.Options))) *BackendClient_ListObjectVersions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *s3.ListObjectVersionsInput
		if args[1] != nil {
			arg1 = args[1].(*s3.ListObjectVersionsInput)
		}
		var arg2 []func(*s3.Options)
		var variadicArgs []func(*s3.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*s3.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *BackendClient_ListObjectVersions_Call) Return(listObjectVersionsOutput *s3.ListObjectVersionsOutput, err error) *BackendClient_ListObjectVersions_Call {
	_c.Call.Return(listObjectVersionsOutput, err)
	return _c
}

func (_c *BackendClient_ListObjectVersions_Call) RunAndReturn(run func(context1 context.Context, listObjectVersionsInput *s3.ListObjectVersionsInput, fns ...func(*s3.Options)) (*s3.ListObjectVersionsOutput, error)) *BackendClient_ListObjectVersions_Call {
	_c.Call.Return(run)
	return _c
}

// ListObjectsV2 provides a mock function for the type BackendClient
func (_mock *BackendClient) ListObjectsV2(context1 context.Context, listObjectsV2Input *s3.ListObjectsV2Input, fns ...func(*s3.Options)) (*s3.ListObjectsV2Output, error) {
	var tmpRet mock.Arguments
	if len(fns) > 0 {
		tmpRet = _mock.Called(context1, listObjectsV2Input, fns)
	} else {
		tmpRet = _mock.Called(context1, listObjectsV2Input)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ListObjectsV2")
	}

	var r0 *s3.ListObjectsV2Output
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.ListObjectsV2Input, ...func(*s3.Options)) (*s3.ListObjectsV2Output, error)); ok {
		return returnFunc(context1, listObjectsV2Input, fns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.ListObjectsV2Input, ...func(*s3.Options)) *s3.ListObjectsV2Output); ok {
		r0 = returnFunc(context1, listObjectsV2Input, fns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*s3.ListObjectsV2Output)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *s3.ListObjectsV2Input, ...func(*s3.Options)) error); ok {
		r1 = returnFunc(context1, listObjectsV2Input, fns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// BackendClient_ListObjectsV2_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListObjectsV2'
type BackendClient_ListObjectsV2_Call struct {
	*mock.Call
}

// ListObjectsV2 is a helper method to define mock.On call
//   - context1 context.Context
//   - listObjectsV2Input *s3.ListObjectsV2Input
//   - fns ...func(*s3.Options)
func (_e *BackendClient_Expecter) ListObjectsV2(context1 interface{}, listObjectsV2Input interface{}, fns ...interface{}) *BackendClient_ListObjectsV2_Call {
	return &BackendClient_ListObjectsV2_Call{Call: _e.mock.On("ListObjectsV2",
		append([]interface{}{context1, listObjectsV2Input}, fns...)...)}
}

func (_c *BackendClient_ListObjectsV2_Call) Run(run func(context1 context.Context, listObjectsV2Input *s3.ListObjectsV2Input, fns ...func(*s3.Options))) *BackendClient_ListObjectsV2_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *s3.ListObjectsV2Input
		if args[1] != nil {
			arg1 = args[1].(*s3.ListObjectsV2Input)
		}
		var arg2 []func(*s3.Options)
		var variadicArgs []func(*s3.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*s3.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *BackendClient_ListObjectsV2_Call) Return(listObjectsV2Output *s3.ListObjectsV2Output, err error) *BackendClient_ListObjectsV2_Call {
	_c.Call.Return(listObjectsV2Output, err)
	return _c
}

func (_c *BackendClient_ListObjectsV2_Call) RunAndReturn(run func(context1 context.Context, listObjectsV2Input *s3.ListObjectsV2Input, fns ...func(*s3.Options)) (*s3.ListObjectsV2Output, error)) *BackendClient_ListObjectsV2_Call {
	_c.Call.Return(run)
	return _c
}

// PutObject provides a mock function for the type BackendClient
func (_mock *BackendClient) PutObject(context1 context.Context, putObjectInput *s3.PutObjectInput, fns ...func(*s3.Options)) (*s3.PutObjectOutput, error) {
	var tmpRet mock.Arguments
	if len(fns) > 0 {
		tmpRet = _mock.Called(context1, putObjectInput, fns)
	} else {
		tmpRet = _mock.Called(context1, putObjectInput)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for PutObject")
	}

	var r0 *s3.PutObjectOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.PutObjectInput, ...func(*s3.Options)) (*s3.PutObjectOutput, error)); ok {
		return returnFunc(context1, putObjectInput, fns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.PutObjectInput, ...func(*s3.Options)) *s3.PutObjectOutput); ok {
		r0 = returnFunc(context1, putObjectInput, fns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*s3.PutObjectOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *s3.PutObjectInput, ...func(*s3.Options)) error); ok {
		r1 = returnFunc(context1, putObjectInput, fns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// BackendClient_PutObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutObject'
type BackendClient_PutObject_Call struct {
	*mock.Call
}

// PutObject is a helper method to define mock.On call
//   - context1 context.Context
//   - putObjectInput *s3.PutObjectInput
//   - fns ...func(*s3.Options)
func (_e *BackendClient_Expecter) PutObject(context1 interface{}, putObjectInput interface{}, fns ...interface{}) *BackendClient_PutObject_Call {
	return &BackendClient_PutObject_Call{Call: _e.mock.On("PutObject",
		append([]interface{}{context1, putObjectInput}, fns...)...)}
}

func (_c *BackendClient_PutObject_Call) Run(run func(context1 context.Context, putObjectInput *s3.PutObjectInput, fns ...func(*s3.Options))) *BackendClient_PutObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *s3.PutObjectInput
		if args[1] != nil {
			arg1 = args[1].(*s3.PutObjectInput)
		}
		var arg2 []func(*s3.Options)
		var variadicArgs []func(*s3.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*s3.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *BackendClient_PutObject_Call) Return(putObjectOutput *s3.PutObjectOutput, err error) *BackendClient_PutObject_Call {
	_c.Call.Return(putObjectOutput, err)
	return _c
}

func (_c *BackendClient_PutObject_Call) RunAndReturn(run func(context1 context.Context, putObjectInput *s3.PutObjectInput, fns ...func(*s3.Options)) (*s3.PutObjectOutput, error)) *BackendClient_PutObject_Call {
	_c.Call.Return(run)
	return _c
}

// UploadPart provides a mock function for the type BackendClient
func (_mock *BackendClient) UploadPart(context1 context.Context, uploadPartInput *s3.UploadPartInput, fns ...func(*s3.Options)) (*s3.UploadPartOutput, error) {
	var tmpRet mock.Arguments
	if len(fns) > 0 {
		tmpRet = _mock.Called(context1, uploadPartInput, fns)
	} else {
		tmpRet = _mock.Called(context1, uploadPartInput)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for UploadPart")
	}

	var r0 *s3.UploadPartOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.UploadPartInput, ...func(*s3.Options)) (*s3.UploadPartOutput, error)); ok {
		return returnFunc(context1, uploadPartInput, fns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.UploadPartInput, ...func(*s3.Options)) *s3.UploadPartOutput); ok {
		r0 = returnFunc(context1, uploadPartInput, fns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*s3.UploadPartOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *s3.UploadPartInput, ...func(*s3.Options)) error); ok {
		r1 = returnFunc(context1, uploadPartInput, fns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// BackendClient_UploadPart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadPart'
type BackendClient_UploadPart_Call struct {
	*mock.Call
}

// UploadPart is a helper method to define mock.On call
//   - context1 context.Context
//   - uploadPartInput *s3.UploadPartInput
//   - fns ...func(*s3.Options)
func (_e *BackendClient_Expecter) UploadPart(context1 interface{}, uploadPartInput interface{}, fns ...interface{}) *BackendClient_UploadPart_Call {
	return &BackendClient_UploadPart_Call{Call: _e.mock.On("UploadPart",
		append([]interface{}{context1, uploadPartInput}, fns...)...)}
}

func (_c *BackendClient_UploadPart_Call) Run(run func(context1 context.Context, uploadPartInput *s3.UploadPartInput, fns ...func(*s3.Options))) *BackendClient_UploadPart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *s3.UploadPartInput
		if args[1] != nil {
			arg1 = args[1].(*s3.UploadPartInput)
		}
		var arg2 []func(*s3.Options)
		var variadicArgs []func(*s3.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*s3.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *BackendClient_UploadPart_Call) Return(uploadPartOutput *s3.UploadPartOutput, err error) *BackendClient_UploadPart_Call {
	_c.Call.Return(uploadPartOutput, err)
	return _c
}

func (_c *BackendClient_UploadPart_Call) RunAndReturn(run func(context1 context.Context, uploadPartInput *s3.UploadPartInput, fns ...func(*s3.Options)) (*s3.UploadPartOutput, error)) *BackendClient_UploadPart_Call {
	_c.Call.Return(run)
	return _c
}
