// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import (
	blob "github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/blob"
	blockblob "github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/blockblob"

	context "context"

	io "io"

	mock "github.com/stretchr/testify/mock"
)

// BlockBlobClient is an autogenerated mock type for the BlockBlobClient type
type BlockBlobClient struct {
	mock.Mock
}

type BlockBlobClient_Expecter struct {
	mock *mock.Mock
}

func (_m *BlockBlobClient) EXPECT() *BlockBlobClient_Expecter {
	return &BlockBlobClient_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, o
func (_m *BlockBlobClient) Delete(ctx context.Context, o *blob.DeleteOptions) (blob.DeleteResponse, error) {
	ret := _m.Called(ctx, o)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 blob.DeleteResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *blob.DeleteOptions) (blob.DeleteResponse, error)); ok {
		return rf(ctx, o)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *blob.DeleteOptions) blob.DeleteResponse); ok {
		r0 = rf(ctx, o)
	} else {
		r0 = ret.Get(0).(blob.DeleteResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *blob.DeleteOptions) error); ok {
		r1 = rf(ctx, o)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BlockBlobClient_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type BlockBlobClient_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - o *blob.DeleteOptions
func (_e *BlockBlobClient_Expecter) Delete(ctx interface{}, o interface{}) *BlockBlobClient_Delete_Call {
	return &BlockBlobClient_Delete_Call{Call: _e.mock.On("Delete", ctx, o)}
}

func (_c *BlockBlobClient_Delete_Call) Run(run func(ctx context.Context, o *blob.DeleteOptions)) *BlockBlobClient_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*blob.DeleteOptions))
	})
	return _c
}

func (_c *BlockBlobClient_Delete_Call) Return(_a0 blob.DeleteResponse, _a1 error) *BlockBlobClient_Delete_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BlockBlobClient_Delete_Call) RunAndReturn(run func(context.Context, *blob.DeleteOptions) (blob.DeleteResponse, error)) *BlockBlobClient_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DownloadStream provides a mock function with given fields: ctx, o
func (_m *BlockBlobClient) DownloadStream(ctx context.Context, o *blob.DownloadStreamOptions) (blob.DownloadStreamResponse, error) {
	ret := _m.Called(ctx, o)

	if len(ret) == 0 {
		panic("no return value specified for DownloadStream")
	}

	var r0 blob.DownloadStreamResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *blob.DownloadStreamOptions) (blob.DownloadStreamResponse, error)); ok {
		return rf(ctx, o)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *blob.DownloadStreamOptions) blob.DownloadStreamResponse); ok {
		r0 = rf(ctx, o)
	} else {
		r0 = ret.Get(0).(blob.DownloadStreamResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *blob.DownloadStreamOptions) error); ok {
		r1 = rf(ctx, o)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BlockBlobClient_DownloadStream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DownloadStream'
type BlockBlobClient_DownloadStream_Call struct {
	*mock.Call
}

// DownloadStream is a helper method to define mock.On call
//   - ctx context.Context
//   - o *blob.DownloadStreamOptions
func (_e *BlockBlobClient_Expecter) DownloadStream(ctx interface{}, o interface{}) *BlockBlobClient_DownloadStream_Call {
	return &BlockBlobClient_DownloadStream_Call{Call: _e.mock.On("DownloadStream", ctx, o)}
}

func (_c *BlockBlobClient_DownloadStream_Call) Run(run func(ctx context.Context, o *blob.DownloadStreamOptions)) *BlockBlobClient_DownloadStream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*blob.DownloadStreamOptions))
	})
	return _c
}

func (_c *BlockBlobClient_DownloadStream_Call) Return(_a0 blob.DownloadStreamResponse, _a1 error) *BlockBlobClient_DownloadStream_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BlockBlobClient_DownloadStream_Call) RunAndReturn(run func(context.Context, *blob.DownloadStreamOptions) (blob.DownloadStreamResponse, error)) *BlockBlobClient_DownloadStream_Call {
	_c.Call.Return(run)
	return _c
}

// GetProperties provides a mock function with given fields: ctx, o
func (_m *BlockBlobClient) GetProperties(ctx context.Context, o *blob.GetPropertiesOptions) (blob.GetPropertiesResponse, error) {
	ret := _m.Called(ctx, o)

	if len(ret) == 0 {
		panic("no return value specified for GetProperties")
	}

	var r0 blob.GetPropertiesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *blob.GetPropertiesOptions) (blob.GetPropertiesResponse, error)); ok {
		return rf(ctx, o)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *blob.GetPropertiesOptions) blob.GetPropertiesResponse); ok {
		r0 = rf(ctx, o)
	} else {
		r0 = ret.Get(0).(blob.GetPropertiesResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *blob.GetPropertiesOptions) error); ok {
		r1 = rf(ctx, o)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BlockBlobClient_GetProperties_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProperties'
type BlockBlobClient_GetProperties_Call struct {
	*mock.Call
}

// GetProperties is a helper method to define mock.On call
//   - ctx context.Context
//   - o *blob.GetPropertiesOptions
func (_e *BlockBlobClient_Expecter) GetProperties(ctx interface{}, o interface{}) *BlockBlobClient_GetProperties_Call {
	return &BlockBlobClient_GetProperties_Call{Call: _e.mock.On("GetProperties", ctx, o)}
}

func (_c *BlockBlobClient_GetProperties_Call) Run(run func(ctx context.Context, o *blob.GetPropertiesOptions)) *BlockBlobClient_GetProperties_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*blob.GetPropertiesOptions))
	})
	return _c
}

func (_c *BlockBlobClient_GetProperties_Call) Return(_a0 blob.GetPropertiesResponse, _a1 error) *BlockBlobClient_GetProperties_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BlockBlobClient_GetProperties_Call) RunAndReturn(run func(context.Context, *blob.GetPropertiesOptions) (blob.GetPropertiesResponse, error)) *BlockBlobClient_GetProperties_Call {
	_c.Call.Return(run)
	return _c
}

// SetMetadata provides a mock function with given fields: ctx, metadata, o
func (_m *BlockBlobClient) SetMetadata(ctx context.Context, metadata map[string]*string, o *blob.SetMetadataOptions) (blob.SetMetadataResponse, error) {
	ret := _m.Called(ctx, metadata, o)

	if len(ret) == 0 {
		panic("no return value specified for SetMetadata")
	}

	var r0 blob.SetMetadataResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, map[string]*string, *blob.SetMetadataOptions) (blob.SetMetadataResponse, error)); ok {
		return rf(ctx, metadata, o)
	}
	if rf, ok := ret.Get(0).(func(context.Context, map[string]*string, *blob.SetMetadataOptions) blob.SetMetadataResponse); ok {
		r0 = rf(ctx, metadata, o)
	} else {
		r0 = ret.Get(0).(blob.SetMetadataResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, map[string]*string, *blob.SetMetadataOptions) error); ok {
		r1 = rf(ctx, metadata, o)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BlockBlobClient_SetMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetMetadata'
type BlockBlobClient_SetMetadata_Call struct {
	*mock.Call
}

// SetMetadata is a helper method to define mock.On call
//   - ctx context.Context
//   - metadata map[string]*string
//   - o *blob.SetMetadataOptions
func (_e *BlockBlobClient_Expecter) SetMetadata(ctx interface{}, metadata interface{}, o interface{}) *BlockBlobClient_SetMetadata_Call {
	return &BlockBlobClient_SetMetadata_Call{Call: _e.mock.On("SetMetadata", ctx, metadata, o)}
}

func (_c *BlockBlobClient_SetMetadata_Call) Run(run func(ctx context.Context, metadata map[string]*string, o *blob.SetMetadataOptions)) *BlockBlobClient_SetMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(map[string]*string), args[2].(*blob.SetMetadataOptions))
	})
	return _c
}

func (_c *BlockBlobClient_SetMetadata_Call) Return(_a0 blob.SetMetadataResponse, _a1 error) *BlockBlobClient_SetMetadata_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BlockBlobClient_SetMetadata_Call) RunAndReturn(run func(context.Context, map[string]*string, *blob.SetMetadataOptions) (blob.SetMetadataResponse, error)) *BlockBlobClient_SetMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// StartCopyFromURL provides a mock function with given fields: ctx, copySource, o
func (_m *BlockBlobClient) StartCopyFromURL(ctx context.Context, copySource string, o *blob.StartCopyFromURLOptions) (blob.StartCopyFromURLResponse, error) {
	ret := _m.Called(ctx, copySource, o)

	if len(ret) == 0 {
		panic("no return value specified for StartCopyFromURL")
	}

	var r0 blob.StartCopyFromURLResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *blob.StartCopyFromURLOptions) (blob.StartCopyFromURLResponse, error)); ok {
		return rf(ctx, copySource, o)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *blob.StartCopyFromURLOptions) blob.StartCopyFromURLResponse); ok {
		r0 = rf(ctx, copySource, o)
	} else {
		r0 = ret.Get(0).(blob.StartCopyFromURLResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *blob.StartCopyFromURLOptions) error); ok {
		r1 = rf(ctx, copySource, o)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BlockBlobClient_StartCopyFromURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartCopyFromURL'
type BlockBlobClient_StartCopyFromURL_Call struct {
	*mock.Call
}

// StartCopyFromURL is a helper method to define mock.On call
//   - ctx context.Context
//   - copySource string
//   - o *blob.StartCopyFromURLOptions
func (_e *BlockBlobClient_Expecter) StartCopyFromURL(ctx interface{}, copySource interface{}, o interface{}) *BlockBlobClient_StartCopyFromURL_Call {
	return &BlockBlobClient_StartCopyFromURL_Call{Call: _e.mock.On("StartCopyFromURL", ctx, copySource, o)}
}

func (_c *BlockBlobClient_StartCopyFromURL_Call) Run(run func(ctx context.Context, copySource string, o *blob.StartCopyFromURLOptions)) *BlockBlobClient_StartCopyFromURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*blob.StartCopyFromURLOptions))
	})
	return _c
}

func (_c *BlockBlobClient_StartCopyFromURL_Call) Return(_a0 blob.StartCopyFromURLResponse, _a1 error) *BlockBlobClient_StartCopyFromURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BlockBlobClient_StartCopyFromURL_Call) RunAndReturn(run func(context.Context, string, *blob.StartCopyFromURLOptions) (blob.StartCopyFromURLResponse, error)) *BlockBlobClient_StartCopyFromURL_Call {
	_c.Call.Return(run)
	return _c
}

// Upload provides a mock function with given fields: ctx, body, options
func (_m *BlockBlobClient) Upload(ctx context.Context, body io.ReadSeekCloser, options *blockblob.UploadOptions) (blockblob.UploadResponse, error) {
	ret := _m.Called(ctx, body, options)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 blockblob.UploadResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, io.ReadSeekCloser, *blockblob.UploadOptions) (blockblob.UploadResponse, error)); ok {
		return rf(ctx, body, options)
	}
	if rf, ok := ret.Get(0).(func(context.Context, io.ReadSeekCloser, *blockblob.UploadOptions) blockblob.UploadResponse); ok {
		r0 = rf(ctx, body, options)
	} else {
		r0 = ret.Get(0).(blockblob.UploadResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, io.ReadSeekCloser, *blockblob.UploadOptions) error); ok {
		r1 = rf(ctx, body, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BlockBlobClient_Upload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upload'
type BlockBlobClient_Upload_Call struct {
	*mock.Call
}

// Upload is a helper method to define mock.On call
//   - ctx context.Context
//   - body io.ReadSeekCloser
//   - options *blockblob.UploadOptions
func (_e *BlockBlobClient_Expecter) Upload(ctx interface{}, body interface{}, options interface{}) *BlockBlobClient_Upload_Call {
	return &BlockBlobClient_Upload_Call{Call: _e.mock.On("Upload", ctx, body, options)}
}

func (_c *BlockBlobClient_Upload_Call) Run(run func(ctx context.Context, body io.ReadSeekCloser, options *blockblob.UploadOptions)) *BlockBlobClient_Upload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(io.ReadSeekCloser), args[2].(*blockblob.UploadOptions))
	})
	return _c
}

func (_c *BlockBlobClient_Upload_Call) Return(_a0 blockblob.UploadResponse, _a1 error) *BlockBlobClient_Upload_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BlockBlobClient_Upload_Call) RunAndReturn(run func(context.Context, io.ReadSeekCloser, *blockblob.UploadOptions) (blockblob.UploadResponse, error)) *BlockBlobClient_Upload_Call {
	_c.Call.Return(run)
	return _c
}

// NewBlockBlobClient creates a new instance of BlockBlobClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBlockBlobClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *BlockBlobClient {
	mock := &BlockBlobClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
