// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import (
	context "context"

	container "github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/container"

	mock "github.com/stretchr/testify/mock"

	runtime "github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime"
)

// ContainerClient is an autogenerated mock type for the ContainerClient type
type ContainerClient struct {
	mock.Mock
}

type ContainerClient_Expecter struct {
	mock *mock.Mock
}

func (_m *ContainerClient) EXPECT() *ContainerClient_Expecter {
	return &ContainerClient_Expecter{mock: &_m.Mock}
}

// GetProperties provides a mock function with given fields: ctx, o
func (_m *ContainerClient) GetProperties(ctx context.Context, o *container.GetPropertiesOptions) (container.GetPropertiesResponse, error) {
	ret := _m.Called(ctx, o)

	if len(ret) == 0 {
		panic("no return value specified for GetProperties")
	}

	var r0 container.GetPropertiesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *container.GetPropertiesOptions) (container.GetPropertiesResponse, error)); ok {
		return rf(ctx, o)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *container.GetPropertiesOptions) container.GetPropertiesResponse); ok {
		r0 = rf(ctx, o)
	} else {
		r0 = ret.Get(0).(container.GetPropertiesResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *container.GetPropertiesOptions) error); ok {
		r1 = rf(ctx, o)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ContainerClient_GetProperties_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProperties'
type ContainerClient_GetProperties_Call struct {
	*mock.Call
}

// GetProperties is a helper method to define mock.On call
//   - ctx context.Context
//   - o *container.GetPropertiesOptions
func (_e *ContainerClient_Expecter) GetProperties(ctx interface{}, o interface{}) *ContainerClient_GetProperties_Call {
	return &ContainerClient_GetProperties_Call{Call: _e.mock.On("GetProperties", ctx, o)}
}

func (_c *ContainerClient_GetProperties_Call) Run(run func(ctx context.Context, o *container.GetPropertiesOptions)) *ContainerClient_GetProperties_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*container.GetPropertiesOptions))
	})
	return _c
}

func (_c *ContainerClient_GetProperties_Call) Return(_a0 container.GetPropertiesResponse, _a1 error) *ContainerClient_GetProperties_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ContainerClient_GetProperties_Call) RunAndReturn(run func(context.Context, *container.GetPropertiesOptions) (container.GetPropertiesResponse, error)) *ContainerClient_GetProperties_Call {
	_c.Call.Return(run)
	return _c
}

// NewListBlobsFlatPager provides a mock function with given fields: o
func (_m *ContainerClient) NewListBlobsFlatPager(o *container.ListBlobsFlatOptions) *runtime.Pager[container.ListBlobsFlatResponse] {
	ret := _m.Called(o)

	if len(ret) == 0 {
		panic("no return value specified for NewListBlobsFlatPager")
	}

	var r0 *runtime.Pager[container.ListBlobsFlatResponse]
	if rf, ok := ret.Get(0).(func(*container.ListBlobsFlatOptions) *runtime.Pager[container.ListBlobsFlatResponse]); ok {
		r0 = rf(o)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*runtime.Pager[container.ListBlobsFlatResponse])
		}
	}

	return r0
}

// ContainerClient_NewListBlobsFlatPager_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewListBlobsFlatPager'
type ContainerClient_NewListBlobsFlatPager_Call struct {
	*mock.Call
}

// NewListBlobsFlatPager is a helper method to define mock.On call
//   - o *container.ListBlobsFlatOptions
func (_e *ContainerClient_Expecter) NewListBlobsFlatPager(o interface{}) *ContainerClient_NewListBlobsFlatPager_Call {
	return &ContainerClient_NewListBlobsFlatPager_Call{Call: _e.mock.On("NewListBlobsFlatPager", o)}
}

func (_c *ContainerClient_NewListBlobsFlatPager_Call) Run(run func(o *container.ListBlobsFlatOptions)) *ContainerClient_NewListBlobsFlatPager_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*container.ListBlobsFlatOptions))
	})
	return _c
}

func (_c *ContainerClient_NewListBlobsFlatPager_Call) Return(_a0 *runtime.Pager[container.ListBlobsFlatResponse]) *ContainerClient_NewListBlobsFlatPager_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ContainerClient_NewListBlobsFlatPager_Call) RunAndReturn(run func(*container.ListBlobsFlatOptions) *runtime.Pager[container.ListBlobsFlatResponse]) *ContainerClient_NewListBlobsFlatPager_Call {
	_c.Call.Return(run)
	return _c
}

// NewListBlobsHierarchyPager provides a mock function with given fields: delimiter, o
func (_m *ContainerClient) NewListBlobsHierarchyPager(delimiter string, o *container.ListBlobsHierarchyOptions) *runtime.Pager[container.ListBlobsHierarchyResponse] {
	ret := _m.Called(delimiter, o)

	if len(ret) == 0 {
		panic("no return value specified for NewListBlobsHierarchyPager")
	}

	var r0 *runtime.Pager[container.ListBlobsHierarchyResponse]
	if rf, ok := ret.Get(0).(func(string, *container.ListBlobsHierarchyOptions) *runtime.Pager[container.ListBlobsHierarchyResponse]); ok {
		r0 = rf(delimiter, o)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*runtime.Pager[container.ListBlobsHierarchyResponse])
		}
	}

	return r0
}

// ContainerClient_NewListBlobsHierarchyPager_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewListBlobsHierarchyPager'
type ContainerClient_NewListBlobsHierarchyPager_Call struct {
	*mock.Call
}

// NewListBlobsHierarchyPager is a helper method to define mock.On call
//   - delimiter string
//   - o *container.ListBlobsHierarchyOptions
func (_e *ContainerClient_Expecter) NewListBlobsHierarchyPager(delimiter interface{}, o interface{}) *ContainerClient_NewListBlobsHierarchyPager_Call {
	return &ContainerClient_NewListBlobsHierarchyPager_Call{Call: _e.mock.On("NewListBlobsHierarchyPager", delimiter, o)}
}

func (_c *ContainerClient_NewListBlobsHierarchyPager_Call) Run(run func(delimiter string, o *container.ListBlobsHierarchyOptions)) *ContainerClient_NewListBlobsHierarchyPager_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(*container.ListBlobsHierarchyOptions))
	})
	return _c
}

func (_c *ContainerClient_NewListBlobsHierarchyPager_Call) Return(_a0 *runtime.Pager[container.ListBlobsHierarchyResponse]) *ContainerClient_NewListBlobsHierarchyPager_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ContainerClient_NewListBlobsHierarchyPager_Call) RunAndReturn(run func(string, *container.ListBlobsHierarchyOptions) *runtime.Pager[container.ListBlobsHierarchyResponse]) *ContainerClient_NewListBlobsHierarchyPager_Call {
	_c.Call.Return(run)
	return _c
}

// NewContainerClient creates a new instance of ContainerClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewContainerClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *ContainerClient {
	mock := &ContainerClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
