name: Go

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.22, 1.23]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: false
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set TMPDIR for Windows
        if: matrix.os == 'windows-latest'
        run: |
          echo "TMPDIR=C:\Temp" >> $GITHUB_ENV
          echo "TEMP=C:\Temp" >> $GITHUB_ENV
          echo "TMP=C:\Temp" >> $GITHUB_ENV
        shell: cmd

      - name: Run Tests
        env:
          TMPDIR: ${{ env.TMPDIR || '' }}
          TEMP: ${{ env.TEMP || '' }}
          TMP: ${{ env.TMP || '' }}
        run: |
          echo "Temporary directory: $TMPDIR"
          go test ./...
