name: Go

on:
  push:
    branches:
      - master
      - feature/fixLint
  pull_request:
    branches:
      - master

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.17, 1.18]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Test
        run: go test ./...
