name: Whitesource Unified Agent Scan - GO

on:
  pull_request:
    branches: [ master* ]


jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -v ./...
      
    - name: WhiteSource Unified Agent Scan
      env:
        WS_APIKEY: ${{secrets.WHITESOURCE_ORG_API_KEY}}
        WS_USERKEY: ${{secrets.WHITESOURCE_PRIORTIZE_USERKEY}}
        WS_WSS_URL: https://saas.whitesourcesoftware.com/agent
        WS_PRODUCTNAME: GH_${{github.event.repository.name}}
        WS_PROJECTNAME: GH_${{github.event.repository.name}}
      run: |
        curl -LJO https://unified-agent.s3.amazonaws.com/wss-unified-agent.jar
        echo Unified Agent downloaded successfully
        java -jar wss-unified-agent.jar