name: Whitesource Unified Agent Scan - GO

on:
  pull_request:
    branches: [ master* ]


jobs:

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_C2FO_GITHUB_ACTIONS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_C2FO_GITHUB_ACTIONS_SECRET }}
        aws-region: us-west-2

    - name: Build
      run: go build -v ./...
      
    - name: WhiteSource Unified Agent Scan
      env:
        WS_APIKEY: ${{secrets.WHITESOURCE_ORG_API_KEY}}
        WS_USERKEY: ${{secrets.WHITESOURCE_PRIORTIZE_USERKEY}}
        WS_WSS_URL: https://saas.whitesourcesoftware.com/agent
        WS_PRODUCTNAME: GH_${{github.event.repository.name}}
        WS_PROJECTNAME: GH_${{github.event.repository.name}}
      run: |
        aws s3api get-object --bucket secops-approved-libraries --key whitesource/wss-unified-agent.jar ./wss-unified-agent.jar
        echo Unified Agent downloaded successfully
        java -jar wss-unified-agent.jar